version: '2'
services:
  web:
    build: .
    command: python3 manage.py runserver 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
  db:
    image: postgres
