version: '3'

services:
  db:
    image: postgres:9.5.5-alpine
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=lwi
  redis:
    image: redis:4.0.9
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: ["./wait-for-it.sh", "db:5432", "--", "./manage.py", "runserver", "0.0.0.0:9002"]
    volumes:
      - .:/code
    ports:
      - "9002:9002"
    depends_on:
      - db
      - redis
    env_file:
      - .env.default
      - .env
  worker:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: celery worker --app=idv
    volumes:
      - .:/code
    links:
      - db
      - redis
    env_file:
      - .env.default
      - .env
    depends_on:
      - db
      - redis
