version: '3'

services:
  db:
    image: postgres:9.5.5-alpine
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=lwi
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: ./manage.py runserver 0.0.0.0:9002
    volumes:
      - .:/code
    ports:
      - "9002:9002"
    depends_on:
      - db
    env_file:
      - .env.default
      - .env
