# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SFTPAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=1024)),
                ('port', models.IntegerField(default=22)),
                ('username', models.CharField(max_length=1024)),
                ('password', models.CharField(max_length=1024)),
                ('base_path', models.CharField(max_length=1024)),
                ('host_key_type', models.CharField(blank=True, max_length=1024, null=True)),
                ('host_key_data', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
