# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mover', '0002_delete_sftpaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveCommandStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.DateTimeField(help_text="When the 'move' command last started and was successful.")),
            ],
        ),
    ]
