# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_accountcredentialindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='s3_key',
            field=models.CharField(max_length=30),
        ),
    ]
