# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_remove_credential_upload_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='status',
            field=models.IntegerField(choices=[(0, 'UNCHECKED'), (1, 'UPLOADED'), (2, 'MISSING'), (3, 'COPIED'), (4, 'MOVED')], default=0),
        ),
    ]
