# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_remove_credential_missing_from_s3'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='copied_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='status',
            field=models.IntegerField(choices=[(0, 'UNCHECKED'), (1, 'FOUND'), (2, 'MISSING'), (3, 'COPIED'), (4, 'MOVED')], default=0),
        ),
    ]
