# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_auto_20160517_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='copied_at',
            field=models.DateTimeField(help_text='When it was copied from Fastway S3 to LW SFTP', null=True),
        ),
    ]
