# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_auto_20160719_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='status',
            field=models.IntegerField(choices=[(0, 'UNCHECKED'), (1, 'FOUND'), (2, 'NOTFOUND'), (3, 'COPIED'), (4, 'MOVED'), (5, 'BLOCKED')], default=0),
        ),
    ]
