# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_auto_20160804_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='has_blocked_extension',
            field=models.BooleanField(default=False),
        ),
    ]
