# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 09:33
from __future__ import unicode_literals

from django.db import migrations

from idv.collector.const import CredentialStatus


def convert_blocked_status_to_flag(apps, schema_editor):
    Credential = apps.get_model('collector', 'Credential')
    Credential.objects.blocked().update(
        has_blocked_extension=True,
        status=CredentialStatus.Found.value
    )


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_credential_has_blocked_extension'),
    ]

    operations = [
        migrations.RunPython(convert_blocked_status_to_flag)
    ]
