# Generated by Django 2.0.6 on 2019-02-12 11:06

from datetime import date
from django.db import migrations, models


def reconcile_proof_of_address(apps, schema_editor):
    Account = apps.get_model('collector', 'Account')
    Account.objects.all().update(
        proof_of_address_date_1=date.min, proof_of_address_date_2=date.min)


def undo_reconcile_proof_of_address(apps, schema_editor):
    Account = apps.get_model('collector', 'Account')
    Account.objects.all().update(
        proof_of_address_date_1=None, proof_of_address_date_2=None)


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_add_proof_of_address_fields'),
    ]

    operations = [
        migrations.RunPython(reconcile_proof_of_address, undo_reconcile_proof_of_address)
    ]
