# Generated by Django 2.0.6 on 2019-02-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_reconcile_proof_of_address_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='proof_of_address_date_1',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='proof_of_address_date_2',
            field=models.DateField(),
        ),
    ]
