# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-29 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftWrapRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('product_description', models.CharField(max_length=500)),
                ('upi', models.CharField(max_length=30, null=True)),
                ('divert_address', models.CharField(max_length=80, null=True)),
                ('divert_contact_name', models.CharField(max_length=80, null=True)),
                ('divert_contact_number', models.CharField(max_length=80, null=True)),
                ('card_message', models.CharField(max_length=600)),
                ('status', models.CharField(choices=[('new', 'NEW'), ('success', 'SUCCESS'), ('failed', 'FAILED'), ('error', 'ERROR')], db_index=True, default='new', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
