# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-06 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftwrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftwraprequest',
            name='card_message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='giftwraprequest',
            name='divert_address',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='giftwraprequest',
            name='divert_contact_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='giftwraprequest',
            name='divert_contact_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='giftwraprequest',
            name='product_description',
            field=models.TextField(),
        ),
    ]
