# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-06 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftwrap', '0002_auto_20161206_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftwraprequest',
            name='upi',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
