# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-05 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftwrap', '0002_auto_20161205_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftwraprequest',
            name='card_message',
            field=models.TextField(max_length=600),
        ),
    ]
