# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftwrap', '0004_auto_20161205_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftwraprequest',
            name='upi',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
