# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-07 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftwrap', '0004_auto_20161207_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftwraprequest',
            name='divert_address1',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='giftwraprequest',
            name='divert_contact_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='giftwraprequest',
            name='divert_contact_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='giftwraprequest',
            name='upi',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
