# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-07 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftwrap', '0005_auto_20161207_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftwraprequest',
            name='divert_address2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='giftwraprequest',
            name='divert_county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='giftwraprequest',
            name='divert_town',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='giftwraprequest',
            name='divert_address1',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
