# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-13 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftwrap', '0006_auto_20161207_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftwraprequest',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('success', 'SUCCESS'), ('failed', 'FAILED'), ('error', 'ERROR'), ('rejected', 'REJECTED')], db_index=True, default='new', max_length=8),
        ),
    ]
