# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-16 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftwrap', '0007_auto_20161213_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftwraprequest',
            name='deliver_by_special_date',
            field=models.BooleanField(default=False),
        ),
    ]
