# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-20 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftwrap', '0008_giftwraprequest_deliver_by_special_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftwraprequest',
            name='deliver_by_special_date',
            field=models.CharField(choices=[('Before', 'BEFORE'), ('On', 'ON')], max_length=8),
        ),
    ]
