# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-01 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftwrap', '0010_auto_20170201_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftwraprequest',
            name='card_message',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
